services:
  - type: web
    name: T3R0ZA_BOT
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    healthCheckPath: /
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: DB_PATH
        value: data/t3r0za.sqlite3
