services:
  - type: web
    name: T3R0ZA_BOT
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: DB_PATH
        value: data/t3r0za.sqlite3
